name: Generate Data
run-name: Fetch and Write Data
on:
  workflow-dispatch
  push:
    branches:
      - 'master'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: install packages
        run: npm ci

      - name: Run index.js
        run: node index.js

      - name: Push
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: "master"
